### PR TITLE
mkversion: Fix replacing of info in Version.d.tpl

### LINKED ISSUE #111: Makd v1.11.0 / v2.1.0 are broken
Running MakD v2.1.0 will yield `sed: -e expression #6, char 29: unknown option to `s'`.
Moreover, `Version.d`'s module name is not replaced, leading to the following code:
```
module @MODULE@;
```

Which obviously fails to compile.

### PR DESCRIPTION
**Pull request by leandro-lucarella-sociomantic**
The replacing of build information in the `Version.d.tpl` is done via a `sed` replace command (`s/@PLACEHOLDER@/$value/`), which can misbehave if the value contain "special" characters (like "/"). This is error prone and unneeded.

The replacement is now done via `awk` using `gsub()`, which performs a very dumb literal search and replace, which is what we need here.

Fixes #111 and should replace #112.

### CODE REVIEW

**Comment by leandro-lucarella-sociomantic** [comment]
This time I tested it with one project and it seems to work fine, but more testing is welcome.

To easily test with other makd versions, I put the merging of this fix to different branches in my fork:

* https://github.com/leandro-lucarella-sociomantic/makd/tree/v1.11.1
* https://github.com/leandro-lucarella-sociomantic/makd/tree/v2.0.3
* https://github.com/leandro-lucarella-sociomantic/makd/tree/v2.1.1

**Review by jens-mueller-sociomantic — COMMENTED** [review]
LGTM.

**Review by nemanja-boric-sociomantic — APPROVED** [review]

**Comment by leandro-lucarella-sociomantic** [comment]
Did anyone actually tested this?

**Comment by nemanja-boric-sociomantic** [comment]
It worked for me (with v1.10.x as a base).

**Comment by nemanja-boric-sociomantic** [comment]
I can confirm v2.1.1 works on the projects previously breaking with v2.1.0.

**Comment by mathias-lang-sociomantic** [comment]
Ditto, works for me on my app (including the new features)

**Pull request merged**
