### PR TITLE
Properly escape $ when getting submodules

### PR DESCRIPTION
**Pull request by leandro-lucarella-sociomantic**

### CODE REVIEW

**Comment by joseph-wakeling-sociomantic** [comment]
Is it intended that this be on top of a clear-release-notes patch?

**Comment by leandro-lucarella-sociomantic** [comment]
No, it should go to v1.8.x, good catch.

**Review by nemanja-boric-sociomantic — DISMISSED** [review]

**Comment by nemanja-boric-sociomantic** [comment]
I suggest one more test and auto-merge ;-)

**Comment by leandro-lucarella-sociomantic** [comment]
Yes, that's why I self assigned, I'll merge after some more testing is done.

**Comment by joseph-wakeling-sociomantic** [comment]
Do the release notes give any indication of the git version required to use it?

I ask because my git (1.9.1) does not support the `--name-only` flag passed to `git config`, which is required for this functionality to work.

**Comment by joseph-wakeling-sociomantic** [comment]
As far as I can tell the `--name-only` flag was introduced in git 2.6.0.  Compare:
https://git-scm.com/docs/git-config/2.5.0
https://git-scm.com/docs/git-config/2.6.0

So seems reasonable to rely on it, but the dependency should be noted in release notes.  Meanwhile I'll get on and add the git PPA and do another test of it after I upgrade ;-)

**Comment by leandro-lucarella-sociomantic** [comment]
Fixed the dependency on a newer Git.

**Comment by leandro-lucarella-sociomantic** [comment]
@joseph-wakeling-sociomantic can you test again?

**Comment by joseph-wakeling-sociomantic** [comment]
Seems to work :-)

**Review by nemanja-boric-sociomantic — APPROVED** [review]

**Comment by leandro-lucarella-sociomantic** [comment]
OK, let's go! :crossed_fingers:

**Pull request merged**
