### PR TITLE
Many small improvements to graph-deps

### PR DESCRIPTION
**Pull request by leandro-lucarella-sociomantic**

### CODE REVIEW

**Comment by nemanja-boric-sociomantic** [comment]
Rebase :-)

**Comment by leandro-lucarella-sociomantic** [comment]
Based on #19, so blocking until is merged.

**Comment by leandro-lucarella-sociomantic** [comment]
Oh, unblocking then :P

**Review by nemanja-boric-sociomantic — APPROVED** [review]

**Comment by nemanja-boric-sociomantic** [comment]
This pull request has been rebased via `git hub pull rebase`. Original pull request HEAD was 21babc6f9517a2ed0cf02a6f55448b159c385fbd, new (rebased) HEAD is 497a15fe5d6fe8a5079054b21df6295ab5fd1b22

**Pull request closed without merging**
