### PR TITLE
Use oceans or druntimes test runner by default

### PR DESCRIPTION
**Pull request by mathias-baumann-sociomantic**

### CODE REVIEW

**Comment by leandro-lucarella-sociomantic** [comment]
> Oh, i didn't see the example code ^^

Let me know if you want to adjust something.

BTW, did you test this? Also, since this is a change in behaviour, I think I will put it in v1.6.x (I can manually merge to v1.x.x as for now it didn't diverged from v1.5.x).

**Comment by mathias-baumann-sociomantic** [comment]
Yes, I did test it

**Comment by mathias-baumann-sociomantic** [comment]
And I'd just leave it now tbh

**Comment by leandro-lucarella-sociomantic** [comment]
Committed via ada30c7

**Comment by leandro-lucarella-sociomantic** [comment]
Related: https://github.com/sociomantic-tsunami/makd/pull/16

**Pull request closed without merging**
