### PR TITLE
Do not output colors for RDMD with DVER=2

### PR DESCRIPTION
**Pull request by llucax**
DMD2 already does it, so by default the path will be in red, and the rest of the message with the right color.

### CODE REVIEW

**Comment by llucax** [comment]
Attached code, and of course GitHub made me the author of this issue because of that... 🙄

**Comment by llucax** [comment]
I did some quick testing and it seems to work, but more test is always welcome...

**Comment by mathias-lang-sociomantic** [comment]
I still got a "participating" notification tho.

**Comment by leandro-lucarella-sociomantic** [comment]
Yeah, the author is in reality preserved, you can see it in the issues listing, is just a bug in this view.

Did you try it?

**Review by mathias-lang-sociomantic — COMMENTED** [review]
> Did you try it?

Just did, works. LGTM.

**Pull request merged**
