### PR TITLE
Remove deprecated Version alias to versionInfo

### PR DESCRIPTION
**Pull request by mathias-lang-sociomantic**
Quite a breaking change right ? :D

### CODE REVIEW

**Review by leandro-lucarella-sociomantic — CHANGES_REQUESTED** [review]
Update release notes please. Since this is not a typical library where we can say "all deprecated features removed" I prefer to be explicit about this change in the release notes :)

**Comment by mihails-strasuns-sociomantic** [comment]
Ping @mathias-lang-sociomantic

**Comment by mathias-lang-sociomantic** [comment]
Done. Although I should probably not be the one clearing RELEASE_NOTES

**Comment by mihails-strasuns-sociomantic** [comment]
LGTM, thanks!

**Pull request merged**
