### PR TITLE
Fix invalid rst table formatting

### PR DESCRIPTION
**Pull request by andreas-bok-sociomantic**
The rst formatting table of supported Major Branches was incorrect

### CODE REVIEW

**Comment by leandro-lucarella-sociomantic** [comment]
Can you redo this against the minor branch of the first version that was broken? (I guess v1.11.x)

**Comment by andreas-bok-sociomantic** [comment]
> Can you redo this against the minor branch of the first version that was broken? (I guess v1.11.x)

Sure

**Comment by andreas-bok-sociomantic** [comment]
Rebased on `v1.11.x`

**Comment by leandro-lucarella-sociomantic** [comment]
It doesn't look like it.

**Comment by leandro-lucarella-sociomantic** [comment]
I will cherry-pick your commit and do a final v1.x.x release set, as today it goes out of support.

**Comment by leandro-lucarella-sociomantic** [comment]
Cherry-picked as a8fc56fd39818b75e559ebc14cc563f0e1e721ea.

**Pull request closed without merging**
